### ISSUE TITLE
Error in ReactHardwareMount.js file

### ISSUE THREAD

**Issue by tiaghoalves** [iamdustan/react-hardware#25]
Hi guys,

I'm trying to connect my Arduino UNO to use with this React renderer, but I have some errors. 
This output comes when I connect my Arduino on the USB Port and them run the command: `npm run example -- basic`

> react-hardware@0.5.0-alpha.2 example /home/tiago/Documentos/react-hardware
> babel-node ./scripts/examples "basic"

> 
> { Error: Cannot find module 'react/lib/ReactInstanceHandles'
>     at Function.Module._resolveFilename (module.js:438:15)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/tiago/Documentos/react-hardware/src/ReactHardwareMount.js:7:1)
>     at Module._compile (module.js:541:32)
>     at loader (/home/tiago/Documentos/react-hardware/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/tiago/Documentos/react-hardware/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12) code: 'MODULE_NOT_FOUND' }
> Error: Cannot find module 'react/lib/ReactInstanceHandles'
>     at Function.Module._resolveFilename (module.js:438:15)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/tiago/Documentos/react-hardware/src/ReactHardwareMount.js:7:1)
>     at Module._compile (module.js:541:32)
>     at loader (/home/tiago/Documentos/react-hardware/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/tiago/Documentos/react-hardware/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)

Dont know what to do now, 'cause I only have one Led in the pin={13} that it's already setup in the index.js file.

Well, I really want to use and even contributing to this project in the future. When I get more knowledge about the React and other dependencies of this project. Thanks, I hope you help me.

**Comment by iamdustan** [comment]
Hey @tiaghoalves, I think you’ll need to update the react version to be more constrained than what it is since we’re depending on internals. Try changing the react version in package.json to `15.3.x` and if that doesn’t work then `15.2.x` and if that doesn’t work `15.1.x` and if that doesn’t work `15.0.x`.

If none of those work I’ll have to go back and find what version I was developing against.

That said, I’m currently updating the project to be a fiber renderer which will be less prone to this sort of issue since it’s not requiring react internals directly.

You can checkout the fiber branch. note that that is installing from a daily build of React so be warned you may hit similar issues. Also, I make no promises not to force-push into that WIP branch.

**Comment by tiaghoalves** [comment]
Yeah thanks, now it works fine for me. I have to change the branch to the fiber, cool.

I've seen that its possible to use it with johnny-five module also, I like it. But I have to ask about the React-DOM. If its possible to use the Hardware without any problem in the Web with the DOM React. 

If yes, there's some example of server code that I can see to take references.

**Comment by iamdustan** [comment]
ReactHardware is intended to be run in a node context, though I think the only hard dependency is on the `serialport` part of the world. Theoretically this could work from in a browser with https://github.com/garrows/browser-serialport.

That said, the webspeech example has the hardware component (in node) with a websocket to a browser app that uses the webspeech API to control the board.

https://github.com/iamdustan/react-hardware/tree/master/examples/webspeech

I’m going to close the issue, though feel free to continue asking questions here.

**Comment by tiaghoalves** [comment]
Ok, this helped me a lot.

Good working for you in the project and keep coding ;)
